services:
  - type: web
    name: churn-api
    env: docker
    plan: starter

# services:
#   - type: web
#     name: churn-api
#     env: python
#     runtime: python-3.11.9
#     buildCommand: pip install -r requirements.txt
#     startCommand: gunicorn app:app
#     plan: starter
